POST http://localhost:4002/produtos HTTP/1.1
content-type: application/json

{
    "name": "Caneta amarela",
    "price": 4
}

###

GET http://localhost:4002/produtos HTTP/1.1

###


GET http://localhost:4002/produtos/{id} HTTP/1.1

###

PUT http://localhost:4002/produtos//{id} HTTP/1.1
content-type: application/json

{
    "name": "Caneta amarela",
    "price": 6
}

###

DELETE http://localhost:4002/produtos//{id}